on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: actions/checkout@v4
        name: Load database
        with:
          ref: gh-pages
          path: .gh-pages

      - name: Generate test files
        run: |
          python --version
          cd data
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

          python data/chunked_btree1_no_filter_1d.py
          python data/chunked_btree1_no_filter_2d.py
          python data/chunked_btree1_shuffle_deflate_1d.py

      - name: Run baseline benchmarks
        run: |
          dotnet --info
          cd baseline
          dotnet run -c Release --job short --filter '*' --project src/Benchmarks/Benchmarks.csproj

      - name: Run dotnet-purehdf benchmarks
        run: |
          dotnet --info
          cd dotnet-purehdf
          dotnet run -c Release --job short --filter '*' --project src/Benchmarks/Benchmarks.csproj

      - name: Run java-jhdf benchmarks
        run: |
          java -version
          cd java-jhdf/test
          mvn --batch-mode clean verify
          java -jar target/benchmarks.jar -rf json

      - name: Run python-pyfive benchmarks
        run: |
          python --version
          cd python-pyfive
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          PYTHONPATH=external/pyfive pytest benchmarks/ --benchmark-json output.json

      - name: Process results
        run: |
          cd processing
          dotnet run

      - name: Store database
        run: |
          cd .gh-pages
          git config --global user.name 'Apollo3zehn'
          git config --global user.email 'apollo3zehn@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "Update database"
          git push